[project]
name = "renderman"
version = "0.1.0"
description = "Project for the Renderman Demos"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "nccapy",
    "pytest",
    "ruff",
    "ncca-ngl>=0.5.3",
    "requests>=2.32.5",
    "tdqm>=0.0.1",
]
